name: build_Release

on:
  workflow_dispatch:

env:
  VERSION: '2.0.5.1'
  BUNDLEID: 'com.zqbb.Dopamine'

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout tools repo
        uses: actions/checkout@main
        with:
          repository: opa334/ChOma
          path: BaseBin/ChOma

      - name: Checkout tools repo
        uses: actions/checkout@main
        with:
          repository: opa334/XPF
          path: BaseBin/XPF

      - name: Checkout tools repo
        uses: actions/checkout@main
        with:
          repository: opa334/opainject
          path: BaseBin/opainject

      - name: Install Dependencies
        run: |
          brew install libarchive ldid make findutils coreutils xcb-util

      - name: Bootstrap Procursus
        uses: w2599/procursus-action@main
        with:
          packages: ldid make findutils coreutils xz-utils

      - name: Pre trustcache
        run: |
          set -x
          git clone https://github.com/CRKatri/trustcache
          cd trustcache
          gmake -j$(sysctl -n hw.physicalcpu) OPENSSL=1
          sudo cp trustcache /opt/procursus/bin/

      - name: Pre theos
        run: |
         curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos > theos
         bash theos

      - name: Pre Bundleid
        run: |
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./Application/Dopamine/Jailbreak/DOPreferenceManager.m
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./Application/Dopamine.xcodeproj/project.pbxproj
          sed -i '' "s/com.opa334.Dopamine/${{ env.BUNDLEID }}/g" ./BaseBin/jbctl/src/main.m

      - name: Pre Version
        run: |
          echo "${{ env.VERSION }}" >./BaseBin/_external/basebin/.version
          sed -i '' 's/MARKETING_VERSION = .*;/MARKETING_VERSION = ${{ env.VERSION }};/g' ./Application/Dopamine.xcodeproj/project.pbxproj

      - name: Pre env
        run: |
         sT=$(TZ=UTC-8 date +'%S')
         echo "msT=$(TZ=UTC-8 date -j -f "%Y-%m-%d %H:%M:%S" "$(TZ=UTC-8 date +'%Y-%m-%d %H:%M'):${sT}" +%s)" >> $GITHUB_ENV
         echo "shT=$(TZ=UTC-8 date +'%Y.%m.%d/%H.%M').${sT}" >> $GITHUB_ENV
         echo "logT=$(TZ=UTC-8 date +'%Y年%m月%d %H:%M'):${sT}" >> $GITHUB_ENV

      - name: Log env
        run: |
         echo ${{ env.VERSION }}
         echo ${{ env.msT }}
         echo ${{ env.shT }}
         echo ${{ env.logT }}

      - name: Precode
        run: |
          sed -i '' "s/AAAA/v${{ env.VERSION }}/g" ./Application/Dopamine/UI/DOMainViewController.m
          sed -i '' "s/AAAB/Don't give up the fun of jailbreaking for upgrading~/g" ./Application/Dopamine/UI/DOMainViewController.m

      - name: Pre body
        run: |
          echo -e "Version: ${{ env.VERSION }}\nCompilation timestamp: ${{ env.msT }}\nBeijing time: ${{ env.shT }}" >> body.txt
          echo -e "\nAdd, delete and modify:" >> body.txt
          echo -e "${{ env.logT }}" >> body.txt
          echo -e "> - Add a new mount button to the setting interface. At the bottom~~" >> body.txt
          echo -e "> - Automatically mount the directory in /var/mobile/newFakePath.plist when jailbreaking" >> body.txt

      # Commented out steps that are placeholders for actual commands
      # - name: Pre keychain
      #   run: |
      # - name: Pre xcode-select
      #   run: |

      - name: Build tipa
        run: |
          set -x
          export THEOS=$HOME/theos
          echo $GITHUB_WORKSPACE
          cd Application/Dopamine/Resources
          bash download_bootstraps.sh
          cd $GITHUB_WORKSPACE
          make CFLAGS="-I/usr/local/opt/libarchive/include" LDFLAGS="-L/usr/local/opt/libarchive/lib"
          mv Application/Dopamine.tipa Dopamine_${{ env.VERSION }}_${{ env.msT }}.tipa

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body_path: body.txt
          prerelease: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa

      - name: Upload Latest Artifact
        id: dopamine-latest-upload
        uses: actions/upload-artifact@v3
        with:
          name: Dopamine_Latest
          path: |
            Dopamine_${{ env.VERSION }}_${{ env.msT }}.tipa
